# Generated by Django 5.1.2 on 2024-10-19 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='word',
            old_name='term',
            new_name='kanji',
        ),
        migrations.RemoveField(
            model_name='word',
            name='example_sentence',
        ),
        migrations.AddField(
            model_name='word',
            name='hiragana',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
