# Generated by Django 5.1.2 on 2024-10-19 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0002_rename_term_word_kanji_remove_word_example_sentence_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='kanji',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
