# Generated by Django 5.1.2 on 2024-10-25 15:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0003_alter_word_kanji'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizresult',
            name='date_taken',
        ),
        migrations.RemoveField(
            model_name='quizresult',
            name='score',
        ),
        migrations.AlterField(
            model_name='quizresult',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='word_quiz_results', to=settings.AUTH_USER_MODEL),
        ),
    ]
