# Generated by Django 5.1.2 on 2024-10-28 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0005_englishword'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitorCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=0)),
            ],
        ),
    ]
