# Generated by Django 5.1.2 on 2024-10-28 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0007_englishword_category_word_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='englishword',
            name='category',
        ),
        migrations.RemoveField(
            model_name='word',
            name='category',
        ),
        migrations.AddField(
            model_name='englishword',
            name='unit',
            field=models.CharField(default='기본 단원', max_length=20),
        ),
        migrations.AddField(
            model_name='word',
            name='unit',
            field=models.CharField(default='기본 단원', max_length=20),
        ),
    ]
