# Generated by Django 5.1.2 on 2024-10-28 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0008_remove_englishword_category_remove_word_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='englishword',
            name='unit',
            field=models.CharField(default='기타', max_length=20),
        ),
    ]
